# --- !Ups
CREATE TABLE IF NOT EXISTS PUBLIC.JUDGE (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
);

INSERT INTO PUBLIC.JUDGE (first_name, last_name) VALUES ('neith','mikkeli');

CREATE TABLE IF NOT EXISTS PUBLIC.WITNESS (
  id INTEGER PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  phone VARCHAR(100)
);


CREATE TABLE IF NOT EXISTS PUBLIC.REPORTS (
  id SERIAL PRIMARY KEY,
  userId INTEGER,
  message TEXT
);

# --- !Downs
DROP TABLE JUDGE;
DROP TABLE WITNESS;
DROP TABLE REPORTS;
